version: 0.2

env:
  variables:
    REPOSITORY_URI: 478681635279.dkr.ecr.us-east-1.amazonaws.com/python_app
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo "Instalando dependencias de Python…"
      - pip install --no-cache-dir -r requirements.txt

  pre_build:
    commands:
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
      - echo "REPOSITORY_URI=$REPOSITORY_URI"
      - echo "Autenticando en Amazon ECR..."
      - aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email | sh

  build:
    commands:
      - echo "✅ Ejecutando tests unitarios…"
      - pytest --maxfail=1 --disable-warnings -q
      - echo "🔧 Construyendo la imagen Docker…"
      - docker build -t python_app .
      - echo "🏷  Etiquetando la imagen para ECR…"
      - docker tag python_app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "📦 Subiendo la imagen a ECR…"
      - docker push $REPOSITORY_URI:latest
      - echo "✅ Push completado."

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json

  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json